import { IMapTaskPosition, tasksEnum } from ".";

export const initialMapTaskPositions: IMapTaskPosition[] = [
  {
    taskTitle: tasksEnum.initialPosition,
    taskNumber: 0,
    cxPointers: 15.8,
    cyPointers: 21,
    cxStep: 16.5,
    cyStep: 32.5,
    users: [],
  },
  {
    taskTitle: tasksEnum.todoList,
    taskNumber: 1,
    cxPointers: 20.8,
    cyPointers: 33.5,
    cxStep: 21.5,
    cyStep: 43.5,
    users: [],
  },
  {
    taskTitle: tasksEnum.taskFromList,
    taskNumber: 2,
    cxPointers: 19.2,
    cyPointers: 64,
    cxStep: 20,
    cyStep: 74,
    users: [],
  },
  {
    taskTitle: tasksEnum.freshAirWalk,
    taskNumber: 3,
    cxPointers: 27.7,
    cyPointers: 69,
    cxStep: 28.5,
    cyStep: 79,
    users: [],
  },
  {
    taskTitle: tasksEnum.gratitudeList,
    taskNumber: 4,
    cxPointers: 44.2,
    cyPointers: 55.5,
    cxStep: 45,
    cyStep: 65.5,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 5,
    cxPointers: 39,
    cyPointers: 41.2,
    cxStep: 40,
    cyStep: 50.8,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 6,
    cxPointers: 32.8,
    cyPointers: 31,
    cxStep: 33.5,
    cyStep: 41,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 7,
    cxPointers: 36,
    cyPointers: 15,
    cxStep: 36.7,
    cyStep: 25,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 8,
    cxPointers: 54.6,
    cyPointers: 15.5,
    cxStep: 55.5,
    cyStep: 25.5,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 9,
    cxPointers: 58.7,
    cyPointers: 30.5,
    cxStep: 59.5,
    cyStep: 40.5,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 10,
    cxPointers: 53.1,
    cyPointers: 53.2,
    cxStep: 54,
    cyStep: 63,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 11,
    cxPointers: 60.2,
    cyPointers: 64,
    cxStep: 61,
    cyStep: 74,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 12,
    cxPointers: 73.6,
    cyPointers: 60.5,
    cxStep: 74.5,
    cyStep: 70.5,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 13,
    cxPointers: 74.7,
    cyPointers: 44.5,
    cxStep: 75.5,
    cyStep: 54.5,
    users: [],
  },
  {
    taskTitle: tasksEnum.goodDeed,
    taskNumber: 14,
    cxPointers: 71.3,
    cyPointers: 29,
    cxStep: 72,
    cyStep: 39,
    users: [],
  },
];
